Divident=int(input("Ingresa el dividend"))
 Divisor=int(input("ingresat el divisor"))
 Quocient= (Dividend) // (Divisor)
Residu= (Dividend)%(Divisor)
print (f"Divisió:{Dividend}/{Divisor}")
print (f"Quocient: {Quocient}")
print (f"Residu: {Residu}")